#配置数据源
spring:
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:sqlserver://${sqlserver_url:10.66.52.77}:${sqlserver_port:1433};DatabaseName=${database_name:OPL}
      username: ${sqlserver_name:sa}
      password: ${sqlserver_password:abc@123456}

  redis:
    #数据库索引
    database: 9
    host: 10.66.52.138
    #host: 10.66.53.27
    port: 6379
    password:
    #连接超时时间
    timeout: 5000


#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
file:
  mac:
    path: ~/upload/file/
    avatar: ~/upload/avatar/
  linux:
    path: /home/eladmin/upload/file/
    avatar: /home/eladmin/upload/avatar/
  windows:
    path: C:\eladmin\upload\file\
    avatar: C:\eladmin\upload\avatar\
  # 文件回显路径
  file-url: file/
  # 头像回显路径
  avatar-url: avatar/

  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 20

# 使用富文本编辑器上传图片需要写死图片存放路径(可根据不同的测试环境更改ip端口)
image-base-url: http://10.65.44.31:8001/avatar/

# 用于上传文件（图纸之类的pdf等文件）
file-base-url: http://10.65.44.31:8001/file/

#静态资源管理根目录
staticFileManager:
  mac: ~/upload/
  windows: C:\eladmin\upload\
  linux: /home/eladmin/upload/

